version: "3.5"

services:
  web:
    build: .
    tty: true
    container_name: odessa-rtsp-server
    restart: always
    #command: node build/rtsp-ws-proxy.js config/streams.yml
    command: node server.js
    volumes:
    - ".:/code"
    ports:
      - 8081:8081
      - 8082:8082
